### PR TITLE
Reduce boost dependencies

### PR DESCRIPTION
**Pull request by ssr-yuki**
Replace boost-depended codes with STL implemented in C++11. 
This PR does not include functional changes.

### CODE REVIEW

**Comment by ssr-yuki** [comment]
I think tests with a real VESC is not required by these changes.

**Review by jsupratman13 — COMMENTED** [review]
two questions:
1. is there a specific reason as to why you want to reduce boost?
2. there are still some places where boost are still used, are you planning to replace those too?

**Comment by ssr-yuki** [comment]
> two questions:
> 
>     1. is there a specific reason as to why you want to reduce boost?
> 
>     2. there are still some places where boost are still used, are you planning to replace those too?

1. These packages have no reason to depend on boost functions that had been merged into C++11. 
2. Partially yes, but not immediately. Using C+++17, we can replace some of the rest, such as `optional`, to STL. On the other hand, we cannot remove all of them even if we introduce the latest C++. More discussion is needed in this problem.

**Review by jsupratman13 — APPROVED** [review]

**Comment by ssr-yuki** [comment]
Thanks!

**Pull request merged**
