### PR TITLE
feat/vcs-repos

### PR DESCRIPTION
**Pull request by saitenntaisei**

### CODE REVIEW

**Review by nyxrobotics — APPROVED** [review]

**Comment by Tacha-S** [comment]
@nyxrobotics Why would you clone the source instead of installing it with rosdep? This seems like an unnecessary change, so I think it should be reverted.

**Comment by nyxrobotics** [comment]
I see that this goes in rosdep, my apologies. Then I don't need this.

**Comment by nyxrobotics** [comment]
@saitenntaisei Is there a reason you wanted to include it from the source?

**Comment by saitenntaisei** [comment]
I did not noticed it could be installed with rosdep (maybe, I forget to do it...). Sorry.

**Pull request merged**
